name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        working-directory: realestate-frontend
        run: npm ci

      # 4. Build project
      - name: Build project
        working-directory: realestate-frontend
        run: npm run build

      # 5. Deploy to GitHub Pages (main branch only)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: realestate-frontend/build

      # 6. Print preview URL
      - name: Print preview URL
        run: |
          BRANCH=${GITHUB_REF_NAME#refs/heads/}
          echo "Preview URL: https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY}/$BRANCH/"
