name: Build and Deploy Frontend

on:
  push:
    branches:
      - main  # Deploy when main branch is updated

permissions:
  contents: write  # Required to push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js 20 (required by react-router >=7)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: ./realestate-frontend

      # 4️⃣ Build project
      - name: Build project
        run: npm run build
        working-directory: ./realestate-frontend

      # 5️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./realestate-frontend/dist
          publish_branch: gh-pages
          # Optional: uncomment if you want to force overwrite
          # force_orphan: true
