name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    # 1. Checkout the repo
    - uses: actions/checkout@v3
    
    # 2. Set up Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # 3. Install dependencies inside realestate-frontend
    - name: Install dependencies
      run: npm ci
      working-directory: ./realestate-frontend

    # 4. Build the React project
    - name: Build
      run: npm run build
      working-directory: ./realestate-frontend

    # 5. Deploy to GitHub Pages from the build folder
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./realestate-frontend/build
